### ISSUE TITLE
TODO: Revamp animation sync system and add compat for blend spaces.

### ISSUE THREAD

**Issue by tristanpoland** [Far-Beyond-Dev/Horizon#156]
We need to upgrade the current basic motion-matching animation synchronization system to improve performance and support blend spaces.

1. Optimize existing animation sync for efficiency
2. Implement blend space support
3. Update network protocol for blend space data (WIP by @tristanpoland )
4. Modify client-side animation system
5. Consider supporting backwards compatibility for the older protocol (This may be more trouble than its worth but could be good practice) 
6. Add developer documentation for the animation system (@tristanpoland )
7. Implement debug visualization tools (@tristanpoland @Tuafo)
8. Conduct thorough testing w/ UE5 template project
9. Optimize for maximum players per instance (make the anims run in the player threads so they get split across CPU cores with their corresponding player)

**Comment by tristanpoland** [comment]
Waiting on https://github.com/Far-Beyond-Dev/Horizon-Plugin-UE5/issues/1 this will be completed as part of that issue's development process

**Comment by tristanpoland** [comment]
@Tuafo This should probably be our next step after #191 is merged. I will be working on rebuilding the players system as a plugin so it will be a good time to pair up and figure out what changes we should make to make this as compatible as possible w/ all engines. I also want to loop in @Caznix as he is familiar with Godot development that way we can ensure we are readily compatible with engines beyond Unreal.

**Comment by Tuafo** [comment]
> @Tuafo This should probably be our next step after #191 is merged. I will be working on rebuilding the players system as a plugin so it will be a good time to pair up and figure out what changes we should make to make this as compatible as possible w/ all engines. I also want to loop in @Caznix as he is familiar with Godot development that way we can ensure we are readily compatible with engines beyond Unreal.

i'll keep on the unreal plugin for horizon!
